### ISSUE TITLE
A review of the programmatic libres configuration

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#238]
**Context**

When implemented, the structure of the dictionary configuring _libres_ was inspired by an early version of the configuration of _Everest_. I've later realized that this configuration was very immature. In addition, we've learned some lessons regarding the configuration of _libres_ lately and I want to put those in use. I hence propose a complete refactoring of the dictionary passed to `ResConfig` to configure _libres_.

**General thoughts**

- I propose that we give ourselves complete freedom in this process. There is no reason to deviate from the current file based configuration just to be different, but where improvements are possible I suggest that we aim at improvement over compatibility.

- If an invalid configuration is passed, we expect the code to say so. In some cases, this is likely to happen in `C`, but in general, we should aim for `Python` exceptions. Later, it would be nice to support some kind of validation of the configuration, but we'll probably save that for later.

- I suggest that we pick a subset of the full space of possible _libres_-configurations and support only those programmatically for now. Then we can expand on this down the line on a on-demand basis.

- Disclaimer: I'm a bit torn on this one! I suggest that we continue to pass the configuration as a Python dictionary for now. I would really like the syntax `config.xxx` instead of `config['xxx']`. In addition I'm a big fan of the immutability of for instance `namedtuples`. However, it is slightly more cumbersome to create something along the lines of a `namedtuple` for the user, no matter if they are to set up a simple configuration of _libres_ in a test, use it in production or load a configuration as `yaml` or similar. If any of you have some thoughts on this one they are very much welcome. But until we have a better solution, I propose sticking with dicts.

- Would it be an idea to expose all the configuration keys in `Python` as lower case versions of the `C` keyword. Are these keys used by anyone else but the configuration part of _libres_, like `ConfigContent`, `ConfigParser` and `ResConfig` (and its ~11 minions)? If not, the only change this would enforce is to lower case all keys in `ConfigKeys.py` and upper case them again when parsing the dictionary in `ResConfig`.

- We should also keep in mind that this is *NOT* an ERT-configuration, but a _libres_ configuration, meaning that if there are settings that are only interpreted by ERT, or possibly should only be a concern for ERT, than I think that is should not en up in the configuration below.

- Also, if there are keys that we plan to deprecate or that is not much used, please point that out and we can leave then out of the loop for now..

**What should be configurable?**
Input on this one is highly appreciated!
- jobname
- job_script
- Installing jobs
- Configuring the forward model (Should we support both `simulation_job` and `forward_model`?)
- num_realizations
- Random seed
- Runpath
- Enspath
- Runpath list
- Log level
- Log file
- queue driver
- queue max submit
- queue max running
- queue min realizations
- Config directory
- Datafile
- Run template
- Eclbase
- Gen kw
- Gen data

*Runner-ups?*
Should we support these as well? (Not supporting them now, is not the same as not supporting them in the near future..
- Refcase
- Obs_config
- History_source
- Summary
- workflows

**Structure of the configuration**
An overview of the configuration dict that can be given to _libres_. I wrote it in `yaml` syntax for increased readability, but when passed to `ResConfig` this will indeed be a python dictionary of similar structure.

```yaml
define:
  CASE_NAME: refactoring4real
  USER: ABCD
  SCRATCH: /scratch/my_super_disk

internals:
  config_directory: /<CASE_NAME>/the/path/to/the/config/file

model:
  num_realizations: 42
  data_file: /my/data_file.ECL
  grid: somegrid.EGRID
  eclbase: eclipse/ECL

environment:
  jobname: myname
  job_script: script.bs
  runpath: <SCRATCH>/%d
  runpath_list: .some_list
  enspath: simulation_results
  random_seed: 54786542654
  log_level: info
  log_file: the_log_file.loglog

install_jobs:
  -
    name: set_up_all
    path: ../../jobs/SET_UP_ALL
  - 
    name: compute_everything
    path: ../../jobs/COMPUTE_EVERYTHING
  -
    name: complete_analysis:
    path: ../../jobs/COMPLETE_ANALYSIS

forward_model:
  - 
    name: set_up_all
    arglist: --include everything/really
  -
    name: compute_everything
  -
    name: complete_analysis
    arglist: --output the_result

queue:
  driver: lsf
  max_submit: 2
  min_realizations: 40
  max_running: 100

data:
  gen_kw:
    -
      name: SIGMA
      template: ../input/templates/sigma.tmpl
      out_file: coarse.sigma
      parameter_file: ../input/distributions/sigma.dist
  
  run_template:
    -
      template: ../input/templates/seed_template.txt
      export: seed.txt
  
  gen_data:
    -
      name: super_data
      result_file: super_data_%d
      report_steps: 1
```
