### ISSUE TITLE
Make minimal poly case yaml configuration

### ISSUE THREAD

**Issue by markusdregi** [equinor/libres#665]
Let us have a discussion about how we would like this configuration to look like

**Comment by oyvindeide** [comment]
```
SIMULATION:
  GEN_DATA:
  - NAME: POLY_RES
    REPORT_STEPS: 0
    RESULT_FILE: poly_%d.out
  INSTALL_JOB:
  - NAME: poly_eval
    PATH: POLY_EVAL
  MIN_REALIZATIONS: 1
  NUM_REALIZATIONS: 20
  OBS_CONFIG: observations
  QUEUE_SYSTEM:
    JOBNAME: poly%d
    MAX_SUBMIT: 50
    QUEUE_SYSTEM: LOCAL
  RUNPATH: poly_out/real_%d/iter_%d
  SIMULATION_JOB:
  - NAME: poly_eval
  TIME_MAP: time_map
```
Here an example of an implementation of the poly case in yaml. When the corresponding `dict` is passed to ResConfig this should run properly.

**Comment by andreabrambilla** [comment]
If this was in ERT, I would argue we would need to move away from this esoteric syntax, make things more self-explaining, and group options that belongs together.
But this issue is in libres and, to be honest, I still don't have a clear idea of how the libres APIs are supposed to look like (in relation to #664 )

**Comment by markusdregi** [comment]
I tried to make a first go at this based on earlier discussions. Note that the parameters and observations are loaded into the project before the configuration and that the configuration after this just reference these.

```yml
parameters:
  - coeffs # <= name from parameter file

results:
  -
    name: poly_res
    type: array
    file: poly.out

observations:
  -
    name: poly_obs # <= name from observation file
    result: poly_res # <= name of corresponding result

model:
  realizations: [0-19]
  min_realizations: 1

environment:
  # real_{realization/iens}/iter_{iter} is appended automatically
  simulation_folder: poly_out

install_jobs:
  -
    name: poly_eval
    path: POLY_EVAL

forward_model:
  - poly_eval

queue_system:
  active_driver: local
  drivers:
    local:
      max_submit: 50
```

A parameters file that has already been internalized in the project
```yaml
-
  name: coeffs
  type: array # formerly known as GEN_KW
  priors:
    -
      name: a
      distribution: uniform
      min: 0
      max: 1
    -
      name: b
      distribution: uniform
      min: 0
      max: 2
    -
      name: c
      distribution: uniform
      min: 0
      max: 5  
```

An observation file that has already been internalized in the project
```yaml
  -
    name: poly_obs
    type: array
    observations:
      -
        value: 2.8532509308
        std: 0.1
      -
        value: 7.20311703432
        std: 1.1
      -
        value: 21.3864899107
        std: 4.1
      -
        value: 31.5145559347
        std: 9.1
      -
        value: 53.5676660405
        std: 16.1
```
