### ISSUE TITLE
ANALYSIS_COPY/ANALYSIS_SET_VAR configuration should be normative, declarative

### ISSUE THREAD

**Issue by jondequinor** [equinor/libres#696]
`ANALYSIS_COPY` currently allows you to _copy_ e.g. module `A` into module `B`, and then configure each with 
```
-- copy A to B
ANALYSIS_LOAD   A  analysis.so
ANALYISIS_COPY  A  B

-- set ENKF_TRUNCATION to differ between A and B
ANALYSIS_SET_VAR A ENKF_TRUNCATION 0.5
ANALYSIS_SET_VAR B ENKF_TRUNCATION 1.5
```

We should deprecate `ANALYSIS_COPY` and aim to have analysis modules be configurable as self contained units in a declarative way. Consider the following YAML:

```
algorithm:
    A:
        ENKF_TRUNCATION: 0.5
    B:
        ENKF_TRUNCATION: 1.5
```

How this is attained is not in the purview of the user, it is an implementation detail. This goes for `ANALYSIS_SET_VAR` as well, this should be a declarative structure.
