### ISSUE TITLE
ANALYSIS_SELECT/ANALYSIS_LOAD should be inferred by some declarative config structure

### ISSUE THREAD

**Issue by jondequinor** [equinor/libres#699]
`ANALYSIS_LOAD` allows you to load arbitrary `.so`-files (modules) that implements the analysis interface. `ANALYSIS_SELECT` will select one of these, or one of the built in modules.

This information could be inferred by capturing the intent of the user. Consider the following configuration:

```
algorithm:
    A:
        path: /home/user/.local/lib/libres_A_analysis_module.so
        enabled: true
        ENKF_TRUNCATION: 0.5
    B:
        path: /home/user/.local/lib/libres_B_analysis_module.so
        enabled: false
        ENKF_TRUNCATION: 1.5
```

The current configuration for loading/selecting analysis modules are an unnecessarily low abstraction layer (imperative instructions instead of declarative "truths").
