### ISSUE TITLE
Restructure scaling job input to allow global defaults for filtering options

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#811]
Currently the input is structured as such:
```
-
    CALCULATE_KEYS:
        threshold: 0.99
        std_cutoff: 1e-6
        alpha: 3.0
        keys:
                - 
                   key: WELL_1
                   index_list: 1-100

-
    CALCULATE_KEYS:
        threshold: 0.95
        keys:
                - 
                   key: WELL_2

```
Probably would like to structure to be:
```
threshold: 0.95
alpha: 1.e-6
std_cutoff: 3
jobs:
  - CALCULATE_KEYS:
      threshold: 0.99
      keys:
        -
          key: WELL_1
          index: 1-5
  - CALCULATE_KEYS:
      keys:
        -
          key: WELL_2
```
where `WELL_2` would use the top level value for threshold (0.95), and `WELL_1` would use 0.99.
